services:
  mimotic.test:
    build:
      context: ./docker
      dockerfile: runtimes/Dockerfile
      args:
        PHP_VERSION: '${PHP_VERSION:-8.3}'
        NODE_VERSION: '${NODE_VERSION:-20}'
        WWWGROUP: '${WWWGROUP:-1000}'
    image: mimotic-php${PHP_VERSION:-8.3}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      PHP_VERSION: '${PHP_VERSION:-8.3}'
    volumes:
      - .:/var/www/html
    networks:
      - mimotic
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME:-mimoticdb}'
      MYSQL_USER: '${DB_USER:-mimoticdbu}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mimotic-mysql:/var/lib/mysql'
    networks:
        - mimotic
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}" ]
      retries: 3
      timeout: 5s
networks:
  mimotic:
    driver: bridge
volumes:
  mimotic-mysql:
    driver: local
